environment:
  logback-folder-path: ${LOGBACK_FOLDER_PATH:./logs}

spring:
  application:
    name: recipes-app
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    show-sql: ${SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}

logging:
  level:
    org.hibernate.sql: ${SQL_LOGGING_LEVEL:INFO}
    org.hibernate.orm.jdbc.bind: ${SQL_BIND_LOGGING_LEVEL:INFO}
    root: ${LOGGING_LEVEL:INFO}
    org.zalando.logbook: ${LOGBOOK_LEVEL:TRACE}
    http.logbook: ${HTTP_LOGBOOK_LEVEL:INFO}

logbook:
  format.style: http
  filter.enabled: true
  predicate:
    include:
      - path: /**